<?php

namespace app\models\image\form;

use yii\base\Model;
use yii\web\UploadedFile;

class UploadForm extends Model
{
    /**
     * @var UploadedFile[]
     */
    public $images;
    public function rules()
    {
                return [['images', 'required'], [['images'], 'file', 'maxFiles' => 5]] ; // TODO: Change the autogenerated stub

    }
    public function upload()
    {

        if ($this->validate()) {
            foreach ($this->images as $image){
                $name = strtolower($image->baseName);
                $image->saveAs('UploadDocument/' . $name . '.' . $image->extension);
            }
            return true;
        } else {
            return false;
        }
    }

}